package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1



/**
 * CodeId generated by hbm2java
 */
public class CodeId  implements java.io.Serializable {


     private int idcode;
     private String userUsername;
     private String languageIdlanguage;

    public CodeId() {
    }

    public CodeId(int idcode, String userUsername, String languageIdlanguage) {
       this.idcode = idcode;
       this.userUsername = userUsername;
       this.languageIdlanguage = languageIdlanguage;
    }
   
    public int getIdcode() {
        return this.idcode;
    }
    
    public void setIdcode(int idcode) {
        this.idcode = idcode;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getLanguageIdlanguage() {
        return this.languageIdlanguage;
    }
    
    public void setLanguageIdlanguage(String languageIdlanguage) {
        this.languageIdlanguage = languageIdlanguage;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CodeId) ) return false;
		 CodeId castOther = ( CodeId ) other; 
         
		 return (this.getIdcode()==castOther.getIdcode())
 && ( (this.getUserUsername()==castOther.getUserUsername()) || ( this.getUserUsername()!=null && castOther.getUserUsername()!=null && this.getUserUsername().equals(castOther.getUserUsername()) ) )
 && ( (this.getLanguageIdlanguage()==castOther.getLanguageIdlanguage()) || ( this.getLanguageIdlanguage()!=null && castOther.getLanguageIdlanguage()!=null && this.getLanguageIdlanguage().equals(castOther.getLanguageIdlanguage()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcode();
         result = 37 * result + ( getUserUsername() == null ? 0 : this.getUserUsername().hashCode() );
         result = 37 * result + ( getLanguageIdlanguage() == null ? 0 : this.getLanguageIdlanguage().hashCode() );
         return result;
   }   


}


