package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Code generated by hbm2java
 */
public class Code  implements java.io.Serializable {


     private CodeId id;
     private Language language;
     private User user;
     private String input;
     private String output;
     private String title;
     private Set rows = new HashSet(0);
     private Set diagrams = new HashSet(0);

    public Code() {
    }

	
    public Code(CodeId id, Language language, User user) {
        this.id = id;
        this.language = language;
        this.user = user;
    }
    public Code(CodeId id, Language language, User user, String input, String output, String title, Set rows, Set diagrams) {
       this.id = id;
       this.language = language;
       this.user = user;
       this.input = input;
       this.output = output;
       this.title = title;
       this.rows = rows;
       this.diagrams = diagrams;
    }
   
    public CodeId getId() {
        return this.id;
    }
    
    public void setId(CodeId id) {
        this.id = id;
    }
    public Language getLanguage() {
        return this.language;
    }
    
    public void setLanguage(Language language) {
        this.language = language;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getInput() {
        return this.input;
    }
    
    public void setInput(String input) {
        this.input = input;
    }
    public String getOutput() {
        return this.output;
    }
    
    public void setOutput(String output) {
        this.output = output;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getRows() {
        return this.rows;
    }
    
    public void setRows(Set rows) {
        this.rows = rows;
    }
    
    public void addRow(Row row){
        this.rows.add(row);
    }
    
    public Set getDiagrams() {
        return this.diagrams;
    }
    
    public void setDiagrams(Set diagrams) {
        this.diagrams = diagrams;
    }




}


