package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1



/**
 * Diagram generated by hbm2java
 */
public class Diagram  implements java.io.Serializable {


     private DiagramId id;
     private Code code;

    public Diagram() {
    }

    public Diagram(DiagramId id, Code code) {
       this.id = id;
       this.code = code;
    }
   
    public DiagramId getId() {
        return this.id;
    }
    
    public void setId(DiagramId id) {
        this.id = id;
    }
    public Code getCode() {
        return this.code;
    }
    
    public void setCode(Code code) {
        this.code = code;
    }




}


