package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language  implements java.io.Serializable {


     private String idlanguage;
     private Set codes = new HashSet(0);

    public Language() {
    }

	
    public Language(String idlanguage) {
        this.idlanguage = idlanguage;
    }
    public Language(String idlanguage, Set codes) {
       this.idlanguage = idlanguage;
       this.codes = codes;
    }
   
    public String getIdlanguage() {
        return this.idlanguage;
    }
    
    public void setIdlanguage(String idlanguage) {
        this.idlanguage = idlanguage;
    }
    public Set getCodes() {
        return this.codes;
    }
    
    public void setCodes(Set codes) {
        this.codes = codes;
    }




}


