package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1



/**
 * Row generated by hbm2java
 */
public class Row  implements java.io.Serializable {


     private RowId id;
     private Code code;
     private Boolean mark;
     private String content;

    public Row() {
    }

	
    public Row(RowId id, Code code, String content) {
        this.id = id;
        this.code = code;
        this.content = content;
    }
    public Row(RowId id, Code code, Boolean mark, String content) {
       this.id = id;
       this.code = code;
       this.mark = mark;
       this.content = content;
    }
   
    public RowId getId() {
        return this.id;
    }
    
    public void setId(RowId id) {
        this.id = id;
    }
    public Code getCode() {
        return this.code;
    }
    
    public void setCode(Code code) {
        this.code = code;
    }
    public Boolean getMark() {
        return this.mark;
    }
    
    public void setMark(Boolean mark) {
        this.mark = mark;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


