package entity;
// Generated 30/06/2016 02:12:41 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String username;
     private String password;
     private Set codes = new HashSet(0);

    public User() {
    }

	
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }
    public User(String username, String password, Set codes) {
       this.username = username;
       this.password = password;
       this.codes = codes;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCodes() {
        return this.codes;
    }
    
    public void setCodes(Set codes) {
        this.codes = codes;
    }




}


